{"uuid":"085aa0cb-c760-4da0-b3fc-afab977ffd67","historyId":"b62e7a899c32f55991a2deebdaec03be","fullName":"com.testng.properties.Expected_Exceptions.checkString","labels":[{"name":"package","value":"com.testng.properties.Expected_Exceptions"},{"name":"testClass","value":"com.testng.properties.Expected_Exceptions"},{"name":"testMethod","value":"checkString"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"com.testng.properties.Expected_Exceptions"},{"name":"host","value":"LAPTOP-ARBCTQD5"},{"name":"thread","value":"19004@LAPTOP-ARBCTQD5.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"checkString","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\nExpected exception of type class java.lang.ArithmeticException but got java.lang.NullPointerException","trace":"org.testng.TestException: \nExpected exception of type class java.lang.ArithmeticException but got java.lang.NullPointerException\r\n\tat org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)\r\n\tat org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:739)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(Unknown Source)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\r\n\tat org.testng.TestNG.run(TestNG.java:1031)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\nCaused by: java.lang.NullPointerException\r\n\tat com.testng.properties.Expected_Exceptions.checkString(Expected_Exceptions.java:16)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\r\n\t... 22 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1664553259921,"stop":1664553259929}